### ISSUE TITLE
[Bug]: Change PA log filepath

### ISSUE THREAD

**Issue by dzane17** [opensearch-project/opensearch-build-libraries#179]
### Describe the bug

PA log has been moved out of `/tmp` dir to `$OPENSEARCH_HOME/logs/PerformanceAnalyzer.log` [PR](https://github.com/opensearch-project/performance-analyzer-rca/pull/315). Please review and update code as needed:
https://github.com/search?q=repo%3Aopensearch-project%2Fopensearch-build-libraries+%2Ftmp%2FPerformanceAnalyzer.log&type=code

**Comment by peterzhuamazon** [comment]
New loc: https://github.com/opensearch-project/performance-analyzer-rca/pull/315

**Comment by peterzhuamazon** [comment]
PR: 
* https://github.com/opensearch-project/opensearch-build-libraries/pull/186
