### ISSUE TITLE
Add latest tag in publishToNpm 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build-libraries#206]
### Is your feature request related to a problem? Please describe

Coming from https://github.com/opensearch-project/opensearch-js/issues/521, looks like we need to [npm-dist-tag](https://docs.npmjs.com/cli/v9/commands/npm-dist-tag) as part of [`publishToNpm`](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/publishToNpm.groovy).

### Describe the solution you'd like

Mark the newly released JS component as latest in npm as part of publishing.

**Comment by gaiksaya** [comment]
Latest is the default behavior AFAIK @dblock. I believe we need an option to "NOT" tag recent release as latest?
https://www.npmjs.com/package/@opensearch-project/opensearch?activeTab=versions
Looks like 1.2.0 was released few weeks ago where was 2.2.1 being latest was released a month ago?

**Comment by bbarani** [comment]
@gaiksaya Looks like you can use this command to tag another version as latest

`npm dist-tag add <pkg name>@<version> latest`

**Comment by gaiksaya** [comment]
Wondering if it might be a good time to introduce something like https://stackoverflow.com/questions/68230173/publishing-a-previous-major-version-to-npm-with-no-tag-and-avoiding-latest
We have been doing this for our docker images where `v1` represents latest of v1.x series and `v2` represents latests version of 2.x series

**Comment by wbeckler** [comment]
I think this command right [here](https://github.com/opensearch-project/opensearch-build-libraries/blob/bfcb1bbfa930e7acd24a363e7710f8c0948e8374/vars/publishToNpm.groovy#L26) is where we need to make sure this is actually the latest, and if not, then override the false addition of "latest" by using --tag [something_other_than+latest] as per https://docs.npmjs.com/adding-dist-tags-to-packages

**Comment by gaiksaya** [comment]
Thanks for bringing this into notice. I missed it. 
> Publishing a package sets the latest tag to the published version unless the --tag option is used. For example, npm publish --tag=beta.
> By default, npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag.

https://docs.npmjs.com/cli/v9/commands/npm-dist-tag#description
Looks like @dblock already opened the bug report. Will work on it soon. 
Thanks!
