### ISSUE TITLE
[Bug]: `gradle-check` alias used in `OpenSearchMetricsQuery`  does not query the latest indices

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/opensearch-build-libraries#493]
### Describe the bug

The library [OpenSearchMetricsQuery.groovy](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/src/gradlecheck/OpenSearchMetricsQuery.groovy) which is used to query the gradle check indices from metrics cluster does not query the latest created `gradle-check-*` indices. The library [publishGradleCheckTestResults.groovy](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/publishGradleCheckTestResults.groovy) creates index in specific date format example as `gradle-check-\$MONTH_YEAR`, the alias `gradle-check` used in in `OpenSearchMetricsQuery` does have the latest indices created from `gradle-check-\$MONTH_YEAR` hence when used the alias `gradle-check` does not give the latest results.

### To reproduce

The command `GET /_alias/gradle-check` does not have all the indices part of `GET /gradle-check-*`

### Expected behavior

```
POST /_aliases
{
  "actions": [
    {
      "add": {
        "index": "gradle-check-*",
        "alias": "gradle-check"
      }
    }
  ]
}
```

### Additional context

The `INDEX_MAPPING` used in [publishGradleCheckTestResults.groovy](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/publishGradleCheckTestResults.groovy) should have the following added to ensure the new index created is part of the `gradle-check` alias.
```
    "aliases": {
      "gradle-check": {}
    }
```

**Comment by prudhvigodithi** [comment]
[Triage]
I will take this up to add the alias `gradke-check` in the index mapping part of [publishGradleCheckTestResults](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/publishGradleCheckTestResults.groovy).

**Comment by prudhvigodithi** [comment]
Closing this as the `GET gradle-check-*/_alias` now targets all the new indices created in past and future.

**Comment by prudhvigodithi** [comment]
Seeing a new error  https://build.ci.opensearch.org/job/gradle-check/52997/console, I assume curl command failing with the underlying OS changes ?
```
INDEX NAME IS gradle-check-02-2025
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   449    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Index does not exist. Creating...
Index created successfully.
Updating alias...
Failed to update alias. Error message: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [${INDEX_NAME}]","index":"${INDEX_NAME}","resource.id":"${INDEX_NAME}","resource.type":"index_or_alias","index_uuid":"_na_"}],"type":"index_not_found_exception","reason":"no such index [${INDEX_NAME}]","index":"${INDEX_NAME}","resource.id":"${INDEX_NAME}","resource.type":"index_or_alias","index_uuid":"_na_"},"status":404}
File Exists, indexing results.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2963  100   819  100  2144  31117  81458 --:--:-- --:--:-- --:--:--  111k
{"took":6,"errors":false,"items":[{"index":{"_index":"gradle-check-02-2025","_id":"fcTbv5QBhoDV_8ni25TC","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}},{"index":{"_index":"gradle-check-02-2025","_id":"fsTbv5QBhoDV_8ni25TC","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}},{"index":{"_index":"gradle-check-02-2025","_id":"f8Tbv5QBhoDV_8ni25TC","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1,"status":201}},{"index":{"_index":"gradle-check-02-2025","_id":"gMTbv5QBhoDV_8ni25TC","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1,"status":201}}]}
```
Adding @peterzhuamazon @gaiksaya

**Comment by gaiksaya** [comment]
I think variable is not getting resolved. `[${INDEX_NAME}]`
If curl did not work, index creation should also fail. However I see `Index created successfully.`

**Comment by peterzhuamazon** [comment]
Hi @prudhvigodithi what OS change you are referring to?
A bit confused why this is an issue.

Thanks.

**Comment by prudhvigodithi** [comment]
Since the Gradle jobs https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/gradle/gradle-check.jenkinsfile#L53 directly run on the EC2 and not on fixed containers, last time the actual issue happened because of the underlying AMI change which broke the bash scripts, so I was wondering it could be the same this time as there is no change in the library code.
Thanks

**Comment by peterzhuamazon** [comment]
I dont think we rebuild that Ubuntu AMI for a long time.

Doubt that is the actual issue tho.
