### ISSUE TITLE
[Bug]: Issue creation fails if the label is not present

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build-libraries#530]
### Describe the bug

The [createGithubIssue](https://github.com/opensearch-project/opensearch-build-libraries/blob/main/vars/createGithubIssue.groovy) library fails if the a label is missing from the repo

### To reproduce

See https://build.ci.opensearch.org/view/Build/job/distribution-build-opensearch/10382/console

```
+ gh issue create --title '[AUTOCUT] Distribution Build Failed for user-behavior-insights-3.0.0' --body '***Build Failed Error***: **user-behavior-insights failed during the distribution build for version: 3.0.0.**
                    Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch/10382/display/redirect.
                    The failed build stage will be marked as unstable :warning: . Please see ./build.sh step for more details.
                    Checkout the [wiki](https://github.com/opensearch-project/opensearch-build/wiki/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution) to reproduce the failure locally.' --label autocut,v3.0.0 --label untriaged --repo https://github.com/opensearch-project/user-behavior-insights.git
could not add label: 'autocut' not found
```

### Expected behavior

Either ignore the label if not present or create a new one.

**Comment by gaiksaya** [comment]
Adding @prudhvigodithi @peterzhuamazon to add thoughts. I think we should create the missing labels instead of ignoring. WDYT?

**Comment by prudhvigodithi** [comment]
The `autocut` is basic label the repo should have and the workflow expects the same, the release labels are auto created with the workflows part of our repo (https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/os-increment-plugin-versions.yml#L103), we can even add a logic if `autocut` does not exist to create one, but with this we will have label creation logic now at multiple places :).

**Comment by gaiksaya** [comment]
> The `autocut` is basic label the repo should have and the jenkins workflow expects the same, the release labels are auto created with the workflows part of our repo (https://github.com/opensearch-project/opensearch-build/blob/main/.github/workflows/os-increment-plugin-versions.yml#L103), we can even add a logic if `autocut` does not exist to create one in the same jenkins workflow, but with this we will have label creation logic now at multiple places :).

That is fine right? If the label exists all the workflows will use the same but for missing ones, not sure if we have any GH command to ignore the label if not present.

**Comment by Divyaasm** [comment]
We can add a check for the label and create a new label if doesn't exist and proceed with the issue creation after label creation.
